#!/bin/sh
APPDIR=`dirname $0`;
HOMEDIR=~/;
java -cp "$APPDIR/src:$APPDIR/bin:$HOMEDIR/script/gwt/gwt-user.jar:$HOMEDIR/script/gwt/gwt-dev.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src edu.nordborglab.client.AccessionConstants  ;

