#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/usr/local/home_ubuntu/crocea/script/gwt/gwt-user.jar:/usr/local/home_ubuntu/crocea/script/gwt/gwt-dev.jar:/home/crocea/script/gwt-maps/gwt-maps.jar:/home/crocea/script/gwt-visualization/gwt-visualization.jar" com.google.gwt.dev.DevMode -startupUrl GWASOnePhenotype.html edu.nordborglab.GWASOnePhenotype;
