#!/bin/sh
project="/srv/GWASWebInterface/GWASWebServer"
cd $project
export PYTHONPATH=/srv/GWASModules

case "$1" in
start)
echo "START DAEMON" >> /tmp/test.log
/usr/local/bin/paster serve --daemon --pid-file=paster.pid --log-file=application.log  production.ini start
;;
stop)
/usr/local/bin/paster serve --daemon --pid-file=paster.pid --log-file=application.log  production.ini stop
;;
restart)
/usr/local/bin/paster serve  --daemon --pid-file=paster.pid --log-file=application.log production.ini restart
;;
*)
echo $"Usage: $0 {start|stop|restart}"
exit 1
esac

